// flow-typed signature: d74e3994eb6374819c277277385c8858
// flow-typed version: <<STUB>>/argon2_v^0.19.3/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'argon2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'argon2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'argon2/argon2' {
  declare module.exports: any;
}

declare module 'argon2/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'argon2/argon2.js' {
  declare module.exports: $Exports<'argon2/argon2'>;
}
declare module 'argon2/test/test.js' {
  declare module.exports: $Exports<'argon2/test/test'>;
}
